# Generated by Django 4.2.7 on 2024-01-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0002_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='startPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
