# Generated by Django 4.2.7 on 2024-01-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0003_availablefont_startpage_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
        migrations.AddField(
            model_name='startpage',
            name='font',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='years.availablefont'),
            preserve_default=False,
        ),
    ]
