# Generated by Django 4.2.7 on 2024-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0004_remove_year_name_startpage_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
