# Generated by Django 4.2.7 on 2024-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0005_startpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='content1',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='content2',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
